language: node_js
sudo: required
dist: trusty


node_js:
  - 4
  - 6
  - 8

env:
  global:
    - TIMEOUT_MULTIPLIER=8

  matrix:
    include:
      - TEST_SUITE=senecajs/seneca-amqp-transport
    exclude:
      - node_js: 4
      - env: TEST_SUITE=senecajs/seneca-amqp-transport

before_script:
  - TEST_SUITE_FOLDER=$(basename $TEST_SUITE)
  - SENECA_INSTALL=https://github.com/senecajs/seneca;
  - echo "TEST_SUITE:$TEST_SUITE"
  - echo "TEST_SUITE_FOLDER:$TEST_SUITE_FOLDER"
  - echo "SENECA_INSTALL:$SENECA_INSTALL";
  - git clone https://github.com/$TEST_SUITE;
  - cd $TEST_SUITE_FOLDER;
  - git checkout v`jq -r ".version" package.json`
  - npm i;
  - npm uninstall seneca;
  - npm install $SENECA_INSTALL;


cache:
  directories:
    - node_modules

